import YourNFTs from "@/components/YourNFTs";
import Head from "next/head";
import React from "react";
import { useAccount } from "wagmi";

export default function Home() {
  const { address, isConnected } = useAccount();

  const onClick = async (e: any) => {};

  return (
    <>
      <Head>
      <title>CrossChainERC721 | Your NFTs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className="flex flex-wrap justify-center text-center w-full">
          <div className="max-w-lg w-full">
            <p className="text-lg text-gray-600">
              Welcome to our NFT minting platform! We are excited to help you
              create unique and valuable NFTs that can be sent to different
              blockchains.
            </p>
          </div>
        </div>
        <div className="">
          {isConnected ? (
            <YourNFTs />
          ) : (
            <p>Connect your wallet to see your assets</p>
          )}
        </div>
      </div>
    </>
  );
}
