import Head from "next/head";

import { NftFormContextProvider } from "@/components/CreateNFTForm/context";

import CreateNFTForm from "@/components/CreateNFTForm";

export default function Home() {
  return (
    <>
      <Head>
      <title>CrossChainERC721 | Mint</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NftFormContextProvider>
        <div className="mx-2 my-8 flex flex-col gap-2 ">
          <div className="flex flex-wrap justify-center text-center w-full">
            <div className="max-w-lg w-full">
            <p className="text-lg text-gray-600">
              Welcome to our NFT minting platform! We are excited to help you
              create unique and valuable NFTs that can be sent to different
              blockchains.
            </p>


            </div>
          </div>
          <div className="flex justify-center">
            <CreateNFTForm />
          </div>
        </div>
      </NftFormContextProvider>
    </>
  );
}
